fixed Documento/Servizio relations after removing servizi_collegati f…
RedTurtle/design.plone.contenttypes pull request #84
Opened 2021-05-25 14:40 UTC by daniele-andreotti

…ield from Documento

2021-05-26 06:46 UTC, cekk requested changes

2021-05-26 06:46 UTC, cekk commented on src/design/plone/contenttypes/upgrades/configure.zcml
> +        title="Update catalog"
Non vedo modifiche al catalog e registry..perché li metti nell'upgrade-step?

2021-05-28 07:40 UTC, daniele-andreotti commented on src/design/plone/contenttypes/upgrades/configure.zcml
> +        title="Update catalog"
Refuso della versione precedente, tolti.

2021-05-28 09:28 UTC, cekk commented
ok, rimane solo da aggiornare i conflitti perché nel frattempo ho fatto una nuova versione

2021-05-28 12:41 UTC, daniele-andreotti commented
Fatto.

2021-05-28 12:57 UTC, cekk approved these changes

2021-05-28 12:57 UTC, merged